#! /bin/sh

sxhkd &
picom --backend glx --blur-method dual_kawase --blur-strength 5 --corner-radius 6 --opacity-rule '10:class_g="Conky"' &
#feh --bg-fill /home/s4vitar/Desktop/s4vitar/Images/Helado.jpg &
#~/.config/polybar/launch.sh &

bspc config pointer_modifier mod1

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
